### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by cysto** [rweather/noise-c#15]
I am not very experienced with cross-compiling, but I gave it a go with MinGW and MSYS on Windows, and I failed miserably.
I assume this library does support compiling for Windows since I saw an #ifdef __WIN32__ in the echo-common.c file.
Could you please enlighten me as to how such a feat could be accomplished?

**Comment by rweather** [comment]
It has been a while since I last did it, but these are the commands I've used in the past.  Different versions of autoconf and mingw require slightly different commands:

    CC=i686-w64-mingw32-gcc ./configure
    CC=x86_64-w64-mingw32-gcc ./configure
    ./configure --host=i686-w64-mingw32
    ./configure --host=x86_64-w64-mingw32

I hope this helps.

**Comment by cysto** [comment]
> ./configure --host=i686-w64-mingw32
./configure --host=x86_64-w64-mingw32

These worked, but when I got to `make`, I encountered some problems with flex.
I don't know if it's it's incompatible with MinGW, but I just ended up compiling using the normal gcc, which generated the missing .c file, then compiled with MinGW and that solved it.

I have yet to test the integrity of the build.
