### ISSUE TITLE
Includes in src/backend/ref

### ISSUE THREAD

**Issue by nazar-pc** [rweather/noise-c#18]
I'm not a C/C++ developer, but still I'm trying to port this library to JavaScript using Emscripten (compile it into WebAssembly).

I'm having some issues with files in `src/backend/ref`. For instance, `#include "internal.h"` doesn't work [here](https://github.com/rweather/noise-c/blob/e3d909c56ece08149e83956fc96255e7b1230715/src/backend/ref/cipher-aesgcm.c#L23). Next few lines also seem to require changes.

From my limited understanding following:
```c
#include "internal.h"
#include "crypto/aes/rijndael-alg-fst.h"
#include "crypto/ghash/ghash.h"
```
Should in fact be like this:
```c
#include <protocol/internal.h>
#include <crypto/aes/rijndael-alg-fst.h>
#include <crypto/ghash/ghash.h>
```

Emscripten uses clang if it makes any difference.

Am I missing something or this is indeed a bug?

**Comment by nazar-pc** [comment]
OK, so it basically work, but requires includes directories to be configured like in makefile

**Comment by rweather** [comment]
No worries - thanks for the feedback anyway. :-)
