### ISSUE TITLE
Rekey() function is not present

### ISSUE THREAD

**Issue by nazar-pc** [rweather/noise-c#24]
Reading through the spec it seems like there should be a function like `noise_cipherstate_rekey()`, but there is none.
Will you add it to match the spec or it is already there, but named differently?

**Comment by rweather** [comment]
That's the plan and I do have a function called exactly than in a private branch on my machine.  I've been working on the changes for rev32 of the Noise specification, but my day job has been eating all my time lately.  Hopefully I'll get some time to finish off the rev32 changes in the next few weeks.

**Comment by nazar-pc** [comment]
`MixKeyAndHash()` on `SymmetricState` is another function missing, but can be relatively easily implemented manually.
